# Pull base image.
FROM arm64v8/ubuntu:20.04

# Environment variables
ARG ARG_WORK_DIR=/mangas-downloader
ENV WORK_DIR=$ARG_WORK_DIR
ENV CONFIG_FILE=$WORK_DIR/config.yml
ENV CRON_PERIOD="0 */6 * * *"

# Settings workspace
WORKDIR $WORK_DIR

# Install package
# Must used calibre package to be able to run external module
ENV DEBIAN_FRONTEND noninteractive
RUN \
  apt-get update        && \
  apt-get upgrade -y    && \
  apt-get install -y       \
            calibre        \
            python3-pip    \
            cron        && \
  rm -rf /var/lib/apt/lists/*
  
# Create the pseudo log file to point to stdout
RUN ln -sf /proc/1/fd/1 /var/log/mangas-downloader.log

# Add scripts
ADD \
  scripts .
# Allow execution on scripts
RUN \
  chmod 754 *.sh

# Add python files
ADD \ 
  sources .
      
# Install python dependencies
RUN \
  pip3 install -r requirements.txt --no-cache-dir
    
# Create manga user
RUN \
  useradd -m -G crontab mangas
RUN \
  chown -R mangas.mangas $WORK_DIR && \
  chown -h mangas.mangas /var/log/mangas-downloader.log
  
# Run the command on container startup
ENTRYPOINT \
  $WORK_DIR/entrypoint.sh
